account/urls.py
from django.conf.urls import url

from account.views import LoginView, LogoutView, ProfileCreateView, ProfileDeleteView, ProfileListView, \
    ProfileUpdateView, ProfileUpdatePasswordView, ProfileDetailView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^create/$', ProfileCreateView.as_view(), name='create_user'),
    url(r'^list/$', ProfileListView.as_view(), name='list_user'),
    url(r'^update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='update_user'),
    url(r'^update/password/(?P<pk>[0-9]+)/$', ProfileUpdatePasswordView.as_view(), name='update_password_user'),
    url(r'^detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='detail_user'),
    url(r'^delete/(?P<pk>[0-9]+)/$', ProfileDeleteView.as_view(), name='delete_user'),
]

airport/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from account.views import DashboardView
from airport import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('account.urls', namespace='account')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^model/', include('model.urls', namespace='model')),
    url(r'^picture/', include('picture.urls', namespace='picture')),
    url(r'^audit/', include('audit.urls', namespace='audit')),
    url(r'^waste/', include('dangerous_waste.urls', namespace='waste')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^bulletin/', include('bulletin.urls', namespace='bulletin')),
    url(r'^training/', include('training.urls', namespace='training')),
    url(r'^environmental/council/', include('environmental_council.urls', namespace='environmental_council')),
    url(r'^bibliography/', include('bibliography.urls', namespace='bibliography')),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audit/urls.py
from django.conf.urls import url

from audit.views import GeneralProgramAuditListView, GeneralProgramAuditDetailView, GeneralProgramAuditCreateView, \
    GeneralProgramAuditUpdateView, GeneralProgramAuditDeleteView, AuditCreateView, AuditDeleteView, AuditUpdateView

urlpatterns = [
    url(r'^general/program/create/$', GeneralProgramAuditCreateView.as_view(),
        name='create_general_program'),
    url(r'^general/program/update/(?P<pk>[0-9]+)/$', GeneralProgramAuditUpdateView.as_view(),
        name='update_general_program'),
    url(r'^general/program/detail/(?P<pk>[0-9]+)/$', GeneralProgramAuditDetailView.as_view(),
        name='detail_general_program'),
    url(r'^general/program/list/$', GeneralProgramAuditListView.as_view(), name='list_general_program'),
    url(r'^general/program/delete/(?P<pk>[0-9]+)/$', GeneralProgramAuditDeleteView.as_view(),
        name='delete_general_program'),

    url(r'^general/program/add/audit/(?P<pk>[0-9]+)/$', AuditCreateView.as_view(), name='create_audit'),
    url(r'^general/program/delete/audit/(?P<pk>[0-9]+)/$', AuditDeleteView.as_view(), name='delete_audit'),
    url(r'^general/program/update/audit/(?P<pk>[0-9]+)/$', AuditUpdateView.as_view(), name='update_audit'),
]

event/urls.py
from django.conf.urls import url

from event.views import EventCreateView, EventListView, EventTodayListView, EventDetailView, EventDeleteView, \
    EventUpdateView

urlpatterns = [
    url(r'^create/$', EventCreateView.as_view(), name='create_event'),
    url(r'^list/$', EventListView.as_view(), name='list_event'),
    url(r'^list/today/$', EventTodayListView.as_view(), name='list_event_today'),
    url(r'^detail/(?P<pk>[0-9]+)/$', EventDetailView.as_view(), name='detail_event'),
    url(r'^update/(?P<pk>[0-9]+)/$', EventUpdateView.as_view(), name='update_event'),
    url(r'^delete/(?P<pk>[0-9]+)/$', EventDeleteView.as_view(), name='delete_event'),
]

model/urls.py
from django.conf.urls import url

from model.views import ModelR01PG01CreateView, ModelR01PG01UpdateView, ModelR01PG01DetailView, ModelR01PG01ListView, \
    ModelR01PG01DeleteView, AreaCreateView, AreaUpdateView, AreaDetailView, AreaListView, AreaDeleteView, \
    LawRequirementCreateView, LawRequirementDeleteView, LawRequirementDetailView, LawRequirementListView, \
    LawRequirementUpdateView, EmergencyReportCreateView, EmergencyReportDeleteView, EmergencyReportDetailView, \
    EmergencyReportListView, EmergencyReportUpdateView, RealAnalysisCreateView, RealAnalysisDeleteView, \
    RealAnalysisDetailView, RealAnalysisListView, RealAnalysisUpdateView, SimulationAnalysisCreateView, \
    SimulationAnalysisDeleteView, SimulationAnalysisDetailView, SimulationAnalysisListView, \
    SimulationAnalysisUpdateView, CommunicationCreateView, CommunicationDeleteView, CommunicationDetailView, \
    CommunicationListView, CommunicationUpdateView, ModelR01PG01ListAllView, EnvironmentalMatrixCreateView, \
    EnvironmentalMatrixUpdateView, EnvironmentalMatrixDetailView, EnvironmentalMatrixDeleteView, \
    EnvironmentalMatrixListView

urlpatterns = [
    url(r'^create/r01pg01/$', ModelR01PG01CreateView.as_view(), name='create_modelr01pg01'),
    url(r'^update/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01UpdateView.as_view(), name='update_modelr01pg01'),
    url(r'^detail/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DetailView.as_view(), name='detail_modelr01pg01'),
    url(r'^list/r01pg01/$', ModelR01PG01ListView.as_view(), name='list_modelr01pg01'),
    url(r'^list/all/r01pg01/$', ModelR01PG01ListAllView.as_view(), name='list_all_modelr01pg01'),
    url(r'^delete/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DeleteView.as_view(), name='delete_modelr01pg01'),

    url(r'^create/area/$', AreaCreateView.as_view(), name='create_area'),
    url(r'^update/area/(?P<pk>[0-9]+)/$', AreaUpdateView.as_view(), name='update_area'),
    url(r'^detail/area/(?P<pk>[0-9]+)/$', AreaDetailView.as_view(), name='detail_area'),
    url(r'^list/area/$', AreaListView.as_view(), name='list_area'),
    url(r'^delete/area/(?P<pk>[0-9]+)/$', AreaDeleteView.as_view(), name='delete_area'),

    url(r'^create/law/$', LawRequirementCreateView.as_view(), name='create_law'),
    url(r'^update/law/(?P<pk>[0-9]+)/$', LawRequirementUpdateView.as_view(), name='update_law'),
    url(r'^detail/law/(?P<pk>[0-9]+)/$', LawRequirementDetailView.as_view(), name='detail_law'),
    url(r'^list/law/$', LawRequirementListView.as_view(), name='list_law'),
    url(r'^delete/law/(?P<pk>[0-9]+)/$', LawRequirementDeleteView.as_view(), name='delete_law'),

    url(r'^create/emergency/$', EmergencyReportCreateView.as_view(), name='create_emergency'),
    url(r'^update/emergency/(?P<pk>[0-9]+)/$', EmergencyReportUpdateView.as_view(), name='update_emergency'),
    url(r'^detail/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDetailView.as_view(), name='detail_emergency'),
    url(r'^list/emergency/$', EmergencyReportListView.as_view(), name='list_emergency'),
    url(r'^delete/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDeleteView.as_view(), name='delete_emergency'),

    url(r'^create/real/analysis/$', RealAnalysisCreateView.as_view(), name='create_real_analysis'),
    url(r'^update/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisUpdateView.as_view(), name='update_real_analysis'),
    url(r'^detail/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDetailView.as_view(), name='detail_real_analysis'),
    url(r'^list/real/analysis/$', RealAnalysisListView.as_view(), name='list_real_analysis'),
    url(r'^delete/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDeleteView.as_view(), name='delete_real_analysis'),

    url(r'^create/simulation/analysis/$', SimulationAnalysisCreateView.as_view(), name='create_simulation_analysis'),
    url(r'^update/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisUpdateView.as_view(),
        name='update_simulation_analysis'),
    url(r'^detail/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDetailView.as_view(),
        name='detail_simulation_analysis'),
    url(r'^list/simulation/analysis/$', SimulationAnalysisListView.as_view(), name='list_simulation_analysis'),
    url(r'^delete/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDeleteView.as_view(),
        name='delete_simulation_analysis'),

    url(r'^create/communication/$', CommunicationCreateView.as_view(), name='create_communication'),
    url(r'^update/communication/(?P<pk>[0-9]+)/$', CommunicationUpdateView.as_view(), name='update_communication'),
    url(r'^detail/communication/(?P<pk>[0-9]+)/$', CommunicationDetailView.as_view(), name='detail_communication'),
    url(r'^list/communication/$', CommunicationListView.as_view(), name='list_communication'),
    url(r'^delete/communication/(?P<pk>[0-9]+)/$', CommunicationDeleteView.as_view(), name='delete_communication'),

    url(r'^create/environmental/matrix/$', EnvironmentalMatrixCreateView.as_view(),
        name='create_environmental_matrix'),
    url(r'^list/environmental/matrix/$', EnvironmentalMatrixListView.as_view(),
        name='list_environmental_matrix'),
    url(r'^update/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixUpdateView.as_view(),
        name='update_environmental_matrix'),
    url(r'^detail/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDetailView.as_view(),
        name='detail_environmental_matrix'),
    url(r'^delete/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDeleteView.as_view(),
        name='delete_environmental_matrix'),

]

picture/urls.py
from django.conf.urls import url

from picture.views import PictureCreateView, PictureListView, PictureDeleteView, PresentationView

urlpatterns = [
    url(r'^create/$', PictureCreateView.as_view(), name='create_picture'),
    url(r'^list/$', PictureListView.as_view(), name='list_picture'),
    url(r'^delete/(?P<pk>[0-9]+)/$', PictureDeleteView.as_view(), name='delete_picture'),
    url(r'^presentation/$', PresentationView.as_view(), name='presentation'),
]

poll/urls.py
from django.conf.urls import url

from poll.views import NationalPassengerPollCreateView, NationalPassengerPollListView, \
    NationalPassengerPollUpdateView, NationalPassengerPollDetailView, \
    NationalPassengerPollDeleteView, AllPollView, InternationalPassengerPollCreateView, \
    InternationalPassengerPollListView, InternationalPassengerPollUpdateView, InternationalPassengerPollDetailView, \
    InternationalPassengerPollDeleteView, AirLineRepresentPollCreateView, AirLineRepresentPollListView, \
    AirLineRepresentPollUpdateView, AirLineRepresentPollDetailView, AirLineRepresentPollDeleteView

urlpatterns = [
    url(r'international/passenger/create/$', InternationalPassengerPollCreateView.as_view(),
        name='create_international_passenger'),
    url(r'international/passenger/list/$', InternationalPassengerPollListView.as_view(),
        name='list_international_passenger'),
    url(r'international/passenger/update/(?P<pk>[0-9]+)/$', InternationalPassengerPollUpdateView.as_view(),
        name='update_international_passenger'),
    url(r'international/passenger/detail/(?P<pk>[0-9]+)/$', InternationalPassengerPollDetailView.as_view(),
        name='detail_international_passenger'),
    url(r'international/passenger/delete/(?P<pk>[0-9]+)/$', InternationalPassengerPollDeleteView.as_view(),
        name='delete_international_passenger'),

    url(r'national/passenger/create/$', NationalPassengerPollCreateView.as_view(),
        name='create_national_passenger'),
    url(r'national/passenger/list/$', NationalPassengerPollListView.as_view(),
        name='list_national_passenger'),
    url(r'national/passenger/update/(?P<pk>[0-9]+)/$', NationalPassengerPollUpdateView.as_view(),
        name='update_national_passenger'),
    url(r'national/passenger/detail/(?P<pk>[0-9]+)/$', NationalPassengerPollDetailView.as_view(),
        name='detail_national_passenger'),
    url(r'national/passenger/delete/(?P<pk>[0-9]+)/$', NationalPassengerPollDeleteView.as_view(),
        name='delete_national_passenger'),

    url(r'airline/represent/create/$', AirLineRepresentPollCreateView.as_view(),
        name='create_airline_represent'),
    url(r'airline/represent/list/$', AirLineRepresentPollListView.as_view(),
        name='list_airline_represent'),
    url(r'airline/represent/update/(?P<pk>[0-9]+)/$', AirLineRepresentPollUpdateView.as_view(),
        name='update_airline_represent'),
    url(r'airline/represent/detail/(?P<pk>[0-9]+)/$', AirLineRepresentPollDetailView.as_view(),
        name='detail_airline_represent'),
    url(r'airline/represent/delete/(?P<pk>[0-9]+)/$', AirLineRepresentPollDeleteView.as_view(),
        name='delete_airline_represent'),

    url(r'all/$', AllPollView.as_view(), name='all_poll'),
]

account/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

SEX_CHOICES = (
    ('M', 'Masculino'),
    ('W', 'Femenino'),
    ('U', 'Sin definir'),
)


def url(self, filename):
    route = 'users/{}/{}'.format(self.username, filename)
    return route


class Profile(User):
    picture = models.ImageField('Imagen', blank=True, null=True, upload_to=url)
    born_date = models.DateField('Fecha de nacimiento', blank=True, null=True)
    gender = models.CharField('Genero', max_length=1, choices=SEX_CHOICES, default='U')
    area = models.ForeignKey('model.Area')

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def age(self):
        actual = timezone.now().year
        born_year = self.born_date.year
        return actual - born_year

    def set_picture(self, picture):
        self.picture = picture

    def __str__(self):
        return self.get_full_name()

account/forms.py
from django import forms

from account.models import Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'picture', 'born_date', 'gender']
        widgets = {
            'born_date': forms.DateInput(attrs={'class': 'datepicker'})
        }


class ProfileUpdatePasswordForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['password']
        widgets = {
            'password': forms.PasswordInput(),
        }


class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['username', 'password', 'is_superuser', 'first_name', 'last_name', 'email', 'is_staff', 'picture',
                  'born_date', 'gender', 'area']
        widgets = {
            'born_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'password': forms.PasswordInput(),
        }

account/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Social Network of University of Holguin">
    <title>Airport - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'account/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/css/icon.css' %}">
    <link rel="stylesheet" href="{% static 'account/css/roboto.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'account/css/ghpages.css' %}">
    <link rel="stylesheet" href="{% static 'account/css/style.css' %}">
    {% block styles %}{% endblock %}

    <script src="{% static 'account/js/jquery-2.0.1.min.js' %}"></script>
    <script src="{% static 'account/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'account/js/materialize.min.js' %}"></script>
    <script src="{% static 'account/js/toastr.min.js' %}"></script>
    <script src="{% static 'account/js/main.js' %}"></script>
</head>
<body>
{% block content %}{% endblock %}

<!--pie de la pagina-->
<footer class="footer page-footer blue">
    <a href="#" class="go-top">Subir</a>
    <div class="footer-copyright">
        <div class="container">
            <span class="hide-on-small-only">
                2015 - 2016 &COPY; Sistema de Gestion Ambiental. Todos los derechos reservados.</span>
        </div>
    </div>
</footer>
<!--fin del pie de la pagina-->


{% block script %}{% endblock %}
</body>
</html>

account/templates/error_403.html
{% extends 'account/dashboard.html' %}

{% block title %}
    No tiene permisos
{% endblock %}

{% block content-down %}
    <div class="container">
        <h2 class="blue-grey-text">Usted no tiene permisos para ingresar a esta página :(</h2>
        <a href="{{ preview }}" class="center">volver</a>
    </div>
{% endblock %}

account/templates/navbar.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <ul id="bibliografic" class="dropdown-content">
        <li>
            <a href="{% url 'event:list_event' %}">
                <div class="blue-text">Efemérides</div>
            </a>
        </li>
        <li>
            <a href="{% url 'model:list_law' %}">
                <div class="blue-text">Normas, Decretos y Leyes</div>
            </a>
        </li>
        <li>
            <a href="{% url 'bibliography:list_cga_bibliography' %}">
                <div class="blue-text">CGA</div>
            </a>
        </li>
        <li>
            <a href="{% url 'bibliography:list_other_bibliography' %}">
                <div class="blue-text">Otros Documentos</div>
            </a>
        </li>
    </ul>

    <ul id="models" class="dropdown-content">
        <li>
            <a href="{% url 'model:list_modelr01pg01' %}">
                <div class="blue-text">R-01 PG.190-01</div>
            </a>
        </li>
        <li>
            <a href="{% url 'model:list_law' %}">
                <div class="blue-text">R-01 PG.190-02</div>
            </a>
        </li>
        <li>
            <a href="{% url 'model:list_emergency' %}">
                <div class="blue-text">R-01 PG.190-03</div>
            </a>
        </li>
        <li>
            <a href="{% url 'model:list_communication' %}">
                <div class="blue-text">R-01 PG.190-04</div>
            </a>
        </li>
        <li>
            <a href="{% url 'audit:list_general_program' %}">
                <div class="blue-text">R-01 PG.190-05</div>
            </a>
        </li>
        <li>
            <a href="{% url 'waste:list_dangerous_waste' %}">
                <div class="blue-text">R-01 PG.190-06</div>
            </a>
        </li>
        <li>
            <a href="{% url 'poll:all_poll' %}">
                <div class="blue-text">R-01 PG.190-07</div>
            </a>
        </li>
    </ul>

    <nav class="nav-wrapper blue" role="navigation">
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <a href="#" data-activates="user-menu" class="button-collapse"><i class="material-icons">account_circle</i></a>
        <ul class="hide-on-med-and-down">
            <li><a href="{% url 'dashboard' %}">Inicio</a></li>
            <li><a href="#" class="dropdown-button" data-activates="models">Modelos</a></li>
            <li><a href="#" class="dropdown-button" data-activates="bibliografic">Bibliografía</a></li>
            <li><a href="{% url 'picture:list_picture' %}">Im&aacute;genes</a></li>
            <li><a href="{% url 'training:list_training' %}">Capacitacion</a></li>
            <li><a href="{% url 'bulletin:list_bulletin' %}">Boletin</a></li>
            <li class="right">
                <a href="#" id="test">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="circle right" width="50" height="50">
                    {% else %}
                        <i class="material-icons right">account_circle</i>
                    {% endif %}
                    Bienvenid@ {{ user.username }}
                </a>
            </li>
        </ul>

        <ul class="side-nav" id="mobile-demo">
            <li><a href="{% url 'dashboard' %}">Inicio</a></li>
            <li><a href="#">Bibliografía</a></li>
        </ul>
    </nav>

    <ul id="slide-out" class="side-nav">
        <li>
            <div class="userView">
                <div class="background">
                    <img src="{% static 'account/images/office.jpg' %}">
                </div>
                {% if profile.picture %}
                    <a href="#"><img class="circle" src="{{ profile.picture.url }}"></a>
                {% else %}
                    <a href="#"><img class="circle" src="{% static 'account/images/user.png' %}"></a>
                {% endif %}
                <a href="#"><span class="white-text name">{{ profile.get_full_name }}</span></a>
                <a href="#"><span class="white-text email">{{ profile.email }}</span></a>
            </div>
        </li>
        <li><a href="{% url 'account:detail_user' profile.pk %}"><i class="material-icons">account_circle</i>Ver perfil</a>
        <li><a href="{% url 'account:update_user' profile.pk %}"><i class="material-icons">mode_edit</i>Editar
            perfil</a></li>
        </li>
        <li>
            <div class="divider"></div>
        </li>
        {% if user.is_superuser %}
            <li><a class="subheader">Herramientas</a></li>
            <li><a href="{% url 'account:list_user' %}">listado de usuarios</a></li>
            <li><a href="{% url 'account:create_user' %}">crear usuario</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'model:list_area' %}">Listado de Areas</a></li>
            <li><a href="{% url 'model:create_area' %}">Crear un Area</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'model:list_law' %}">Todas las leyes</a></li>
            <li><a href="{% url 'model:create_law' %}">Subir una ley</a></li>
            <li class="divider"></li>
        {% endif %}
        <li class="subheader">Im&aacute;genes</li>
        <li><a href="{% url 'picture:list_picture' %}">Todas las im&aacute;genes</a></li>
        {% if user.is_superuser %}
            <li><a href="{% url 'picture:create_picture' %}">subir una imagen</a></li>
        {% endif %}
        <li class="divider"></li>
        <li><a href="{% url 'account:logout' %}"><i class="material-icons">input</i>Salir</a></li>
    </ul>

    <a href="#" data-activates="slide-out" class="button-collapse hide" id="clicking"><i class="material-icons">menu</i></a>
    {% block content-down %}{% endblock %}
{% endblock %}
{% block script %}
    <script>
        $('#test').click(function () {
            $('#clicking').click();
        });
        {#        $('.datepicker').pickadate({#}
        {#            selectMonths: false, // Creates a dropdown to control month#}
        {#            selectYears: 50, // Creates a dropdown of 50 years to control year#}
        {#            format: "yyyy"#}
        {#        });#}
    </script>
{% endblock %}