account/urls.py
from django.conf.urls import url

from account.views import LoginView, LogoutView, ProfileCreateView, ProfileDeleteView, ProfileListView, \
    ProfileUpdateView, ProfileUpdatePasswordView, ProfileDetailView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^create/$', ProfileCreateView.as_view(), name='create_user'),
    url(r'^list/$', ProfileListView.as_view(), name='list_user'),
    url(r'^update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='update_user'),
    url(r'^update/password/(?P<pk>[0-9]+)/$', ProfileUpdatePasswordView.as_view(), name='update_password_user'),
    url(r'^detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='detail_user'),
    url(r'^delete/(?P<pk>[0-9]+)/$', ProfileDeleteView.as_view(), name='delete_user'),
]

airport/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from account.views import DashboardView
from airport import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('account.urls', namespace='account')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^model/', include('model.urls', namespace='model')),
    url(r'^picture/', include('picture.urls', namespace='picture')),
    url(r'^audit/', include('audit.urls', namespace='audit')),
    url(r'^waste/', include('dangerous_waste.urls', namespace='waste')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^bulletin/', include('bulletin.urls', namespace='bulletin')),
    url(r'^training/', include('training.urls', namespace='training')),
    url(r'^environmental/council/', include('environmental_council.urls', namespace='environmental_council')),
    url(r'^bibliography/', include('bibliography.urls', namespace='bibliography')),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audit/urls.py
from django.conf.urls import url

from audit.views import GeneralProgramAuditListView, GeneralProgramAuditDetailView, GeneralProgramAuditCreateView, \
    GeneralProgramAuditUpdateView, GeneralProgramAuditDeleteView, AuditCreateView, AuditDeleteView, AuditUpdateView

urlpatterns = [
    url(r'^general/program/create/$', GeneralProgramAuditCreateView.as_view(),
        name='create_general_program'),
    url(r'^general/program/update/(?P<pk>[0-9]+)/$', GeneralProgramAuditUpdateView.as_view(),
        name='update_general_program'),
    url(r'^general/program/detail/(?P<pk>[0-9]+)/$', GeneralProgramAuditDetailView.as_view(),
        name='detail_general_program'),
    url(r'^general/program/list/$', GeneralProgramAuditListView.as_view(), name='list_general_program'),
    url(r'^general/program/delete/(?P<pk>[0-9]+)/$', GeneralProgramAuditDeleteView.as_view(),
        name='delete_general_program'),

    url(r'^general/program/add/audit/(?P<pk>[0-9]+)/$', AuditCreateView.as_view(), name='create_audit'),
    url(r'^general/program/delete/audit/(?P<pk>[0-9]+)/$', AuditDeleteView.as_view(), name='delete_audit'),
    url(r'^general/program/update/audit/(?P<pk>[0-9]+)/$', AuditUpdateView.as_view(), name='update_audit'),
]

model/urls.py
from django.conf.urls import url

from model.views import ModelR01PG01CreateView, ModelR01PG01UpdateView, ModelR01PG01DetailView, ModelR01PG01ListView, \
    ModelR01PG01DeleteView, AreaCreateView, AreaUpdateView, AreaDetailView, AreaListView, AreaDeleteView, \
    LawRequirementCreateView, LawRequirementDeleteView, LawRequirementDetailView, LawRequirementListView, \
    LawRequirementUpdateView, EmergencyReportCreateView, EmergencyReportDeleteView, EmergencyReportDetailView, \
    EmergencyReportListView, EmergencyReportUpdateView, RealAnalysisCreateView, RealAnalysisDeleteView, \
    RealAnalysisDetailView, RealAnalysisListView, RealAnalysisUpdateView, SimulationAnalysisCreateView, \
    SimulationAnalysisDeleteView, SimulationAnalysisDetailView, SimulationAnalysisListView, \
    SimulationAnalysisUpdateView, CommunicationCreateView, CommunicationDeleteView, CommunicationDetailView, \
    CommunicationListView, CommunicationUpdateView, ModelR01PG01ListAllView, EnvironmentalMatrixCreateView, \
    EnvironmentalMatrixUpdateView, EnvironmentalMatrixDetailView, EnvironmentalMatrixDeleteView, \
    EnvironmentalMatrixListView

urlpatterns = [
    url(r'^create/r01pg01/$', ModelR01PG01CreateView.as_view(), name='create_modelr01pg01'),
    url(r'^update/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01UpdateView.as_view(), name='update_modelr01pg01'),
    url(r'^detail/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DetailView.as_view(), name='detail_modelr01pg01'),
    url(r'^list/r01pg01/$', ModelR01PG01ListView.as_view(), name='list_modelr01pg01'),
    url(r'^list/all/r01pg01/$', ModelR01PG01ListAllView.as_view(), name='list_all_modelr01pg01'),
    url(r'^delete/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DeleteView.as_view(), name='delete_modelr01pg01'),

    url(r'^create/area/$', AreaCreateView.as_view(), name='create_area'),
    url(r'^update/area/(?P<pk>[0-9]+)/$', AreaUpdateView.as_view(), name='update_area'),
    url(r'^detail/area/(?P<pk>[0-9]+)/$', AreaDetailView.as_view(), name='detail_area'),
    url(r'^list/area/$', AreaListView.as_view(), name='list_area'),
    url(r'^delete/area/(?P<pk>[0-9]+)/$', AreaDeleteView.as_view(), name='delete_area'),

    url(r'^create/law/$', LawRequirementCreateView.as_view(), name='create_law'),
    url(r'^update/law/(?P<pk>[0-9]+)/$', LawRequirementUpdateView.as_view(), name='update_law'),
    url(r'^detail/law/(?P<pk>[0-9]+)/$', LawRequirementDetailView.as_view(), name='detail_law'),
    url(r'^list/law/$', LawRequirementListView.as_view(), name='list_law'),
    url(r'^delete/law/(?P<pk>[0-9]+)/$', LawRequirementDeleteView.as_view(), name='delete_law'),

    url(r'^create/emergency/$', EmergencyReportCreateView.as_view(), name='create_emergency'),
    url(r'^update/emergency/(?P<pk>[0-9]+)/$', EmergencyReportUpdateView.as_view(), name='update_emergency'),
    url(r'^detail/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDetailView.as_view(), name='detail_emergency'),
    url(r'^list/emergency/$', EmergencyReportListView.as_view(), name='list_emergency'),
    url(r'^delete/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDeleteView.as_view(), name='delete_emergency'),

    url(r'^create/real/analysis/$', RealAnalysisCreateView.as_view(), name='create_real_analysis'),
    url(r'^update/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisUpdateView.as_view(), name='update_real_analysis'),
    url(r'^detail/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDetailView.as_view(), name='detail_real_analysis'),
    url(r'^list/real/analysis/$', RealAnalysisListView.as_view(), name='list_real_analysis'),
    url(r'^delete/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDeleteView.as_view(), name='delete_real_analysis'),

    url(r'^create/simulation/analysis/$', SimulationAnalysisCreateView.as_view(), name='create_simulation_analysis'),
    url(r'^update/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisUpdateView.as_view(),
        name='update_simulation_analysis'),
    url(r'^detail/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDetailView.as_view(),
        name='detail_simulation_analysis'),
    url(r'^list/simulation/analysis/$', SimulationAnalysisListView.as_view(), name='list_simulation_analysis'),
    url(r'^delete/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDeleteView.as_view(),
        name='delete_simulation_analysis'),

    url(r'^create/communication/$', CommunicationCreateView.as_view(), name='create_communication'),
    url(r'^update/communication/(?P<pk>[0-9]+)/$', CommunicationUpdateView.as_view(), name='update_communication'),
    url(r'^detail/communication/(?P<pk>[0-9]+)/$', CommunicationDetailView.as_view(), name='detail_communication'),
    url(r'^list/communication/$', CommunicationListView.as_view(), name='list_communication'),
    url(r'^delete/communication/(?P<pk>[0-9]+)/$', CommunicationDeleteView.as_view(), name='delete_communication'),

    url(r'^create/environmental/matrix/$', EnvironmentalMatrixCreateView.as_view(),
        name='create_environmental_matrix'),
    url(r'^list/environmental/matrix/$', EnvironmentalMatrixListView.as_view(),
        name='list_environmental_matrix'),
    url(r'^update/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixUpdateView.as_view(),
        name='update_environmental_matrix'),
    url(r'^detail/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDetailView.as_view(),
        name='detail_environmental_matrix'),
    url(r'^delete/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDeleteView.as_view(),
        name='delete_environmental_matrix'),

]

poll/urls.py
from django.conf.urls import url

from poll.views import NationalPassengerPollCreateView, NationalPassengerPollListView, \
    NationalPassengerPollUpdateView, NationalPassengerPollDetailView, \
    NationalPassengerPollDeleteView, AllPollView, InternationalPassengerPollCreateView, \
    InternationalPassengerPollListView, InternationalPassengerPollUpdateView, InternationalPassengerPollDetailView, \
    InternationalPassengerPollDeleteView, AirLineRepresentPollCreateView, AirLineRepresentPollListView, \
    AirLineRepresentPollUpdateView, AirLineRepresentPollDetailView, AirLineRepresentPollDeleteView

urlpatterns = [
    url(r'international/passenger/create/$', InternationalPassengerPollCreateView.as_view(),
        name='create_international_passenger'),
    url(r'international/passenger/list/$', InternationalPassengerPollListView.as_view(),
        name='list_international_passenger'),
    url(r'international/passenger/update/(?P<pk>[0-9]+)/$', InternationalPassengerPollUpdateView.as_view(),
        name='update_international_passenger'),
    url(r'international/passenger/detail/(?P<pk>[0-9]+)/$', InternationalPassengerPollDetailView.as_view(),
        name='detail_international_passenger'),
    url(r'international/passenger/delete/(?P<pk>[0-9]+)/$', InternationalPassengerPollDeleteView.as_view(),
        name='delete_international_passenger'),

    url(r'national/passenger/create/$', NationalPassengerPollCreateView.as_view(),
        name='create_national_passenger'),
    url(r'national/passenger/list/$', NationalPassengerPollListView.as_view(),
        name='list_national_passenger'),
    url(r'national/passenger/update/(?P<pk>[0-9]+)/$', NationalPassengerPollUpdateView.as_view(),
        name='update_national_passenger'),
    url(r'national/passenger/detail/(?P<pk>[0-9]+)/$', NationalPassengerPollDetailView.as_view(),
        name='detail_national_passenger'),
    url(r'national/passenger/delete/(?P<pk>[0-9]+)/$', NationalPassengerPollDeleteView.as_view(),
        name='delete_national_passenger'),

    url(r'airline/represent/create/$', AirLineRepresentPollCreateView.as_view(),
        name='create_airline_represent'),
    url(r'airline/represent/list/$', AirLineRepresentPollListView.as_view(),
        name='list_airline_represent'),
    url(r'airline/represent/update/(?P<pk>[0-9]+)/$', AirLineRepresentPollUpdateView.as_view(),
        name='update_airline_represent'),
    url(r'airline/represent/detail/(?P<pk>[0-9]+)/$', AirLineRepresentPollDetailView.as_view(),
        name='detail_airline_represent'),
    url(r'airline/represent/delete/(?P<pk>[0-9]+)/$', AirLineRepresentPollDeleteView.as_view(),
        name='delete_airline_represent'),

    url(r'all/$', AllPollView.as_view(), name='all_poll'),
]

audit/models.py
from django.core.exceptions import ValidationError
from django.db import models

from account.models import Profile
from model.models import Area

AUDIT_TYPE = (
    ('nc', 'Auditoría Nivel Central'),
    ('sgc', 'Auditoría al SGC'),
    ('z', 'Auditoría de la UEB Aeropuerto'),
    ('sga', 'Auditoría al SGA'),
    ('e', 'Auditoría de la Especialidad (UEB Nacionales)'),
    ('sgi', 'Auditoría al SGICH'),
    ('bv', 'Auditoría de Bureau Veritas'),
    ('ai', 'Auditoría Integrada'),
)


def validate_month(value):
    if value > 12 or value < 1:
        raise ValidationError(
            '%(value)s no es un mes válido. NOTA: el mes debe estar entre 1 y 12',
            params={'value': value},
        )


MONTH = {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre',
}


class GeneralProgramAudit(models.Model):
    code = 'R-01/PG.01-05'
    # audit = models.ForeignKey(Audit, verbose_name='Auditoria')
    observations = models.TextField('Observaciones')
    made_by = models.ForeignKey(Profile, verbose_name='Elaborado por')
    date = models.DateField('Fecha', auto_now=True)

    class Meta:
        verbose_name = 'Programa General'
        verbose_name_plural = 'Programas Generales'

    def __str__(self):
        return '{} {}'.format(self.code, self.observations)


class Audit(models.Model):
    area = models.ForeignKey(Area, verbose_name='Area')
    general_program = models.ForeignKey(GeneralProgramAudit, verbose_name='Programa general')
    e = models.CharField('Enero', choices=AUDIT_TYPE, blank=True, max_length=3)
    f = models.CharField('Febrero', choices=AUDIT_TYPE, blank=True, max_length=3)
    ma = models.CharField('Marzo', choices=AUDIT_TYPE, blank=True, max_length=3)
    ab = models.CharField('Abril', choices=AUDIT_TYPE, blank=True, max_length=3)
    m = models.CharField('Mayo', choices=AUDIT_TYPE, blank=True, max_length=3)
    j = models.CharField('Junio', choices=AUDIT_TYPE, blank=True, max_length=3)
    ju = models.CharField('Julio', choices=AUDIT_TYPE, blank=True, max_length=3)
    a = models.CharField('Agosto', choices=AUDIT_TYPE, blank=True, max_length=3)
    s = models.CharField('Septiembre', choices=AUDIT_TYPE, blank=True, max_length=3)
    o = models.CharField('Octubre', choices=AUDIT_TYPE, blank=True, max_length=3)
    n = models.CharField('Noviembre', choices=AUDIT_TYPE, blank=True, max_length=3)
    d = models.CharField('Diciembre', choices=AUDIT_TYPE, blank=True, max_length=3)

    class Meta:
        verbose_name = 'Auditoria'
        verbose_name_plural = 'Auditorias'

    def __str__(self):
        return '{} {}'.format(self.area, self.general_program)


class AuditPlan(models.Model):
    code = 'R-02/PG.01-05'
    pass


class VerifyList(models.Model):
    code = 'R-03/PG.01-05'
    pass


class AuditInform(models.Model):
    code = 'R-04/PG.01-05'
    pass


class AuditControl(models.Model):
    code = 'R-05/PG.01-05'
    pass

audit/forms.py
from django import forms

from audit.models import Audit


class AuditForm(forms.ModelForm):
    class Meta:
        model = Audit
        exclude = ['general_program']

audit/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from account.models import Profile
from account.views import ProfileMixin, SuperUserRequiredMixin
from audit.models import Audit, GeneralProgramAudit
from audit.forms import AuditForm


class GeneralProgramAuditListView(ProfileMixin, ListView):
    template_name = 'audit/general_program_list.html'
    model = GeneralProgramAudit
    context_object_name = 'general_program_list'


class GeneralProgramAuditUpdateView(SuperUserRequiredMixin, UpdateView):
    model = GeneralProgramAudit
    fields = ['observations', 'made_by']
    template_name = 'audit/general_program_form.html'

    def get_success_url(self):
        return reverse_lazy('audit:detail_general_program', kwargs={'pk': self.object.pk})


class GeneralProgramAuditCreateView(SuperUserRequiredMixin, CreateView):
    model = GeneralProgramAudit
    fields = ['observations']
    template_name = 'audit/general_program_form.html'

    def get_success_url(self):
        return reverse_lazy('audit:detail_general_program', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.made_by = Profile.objects.get(username=self.request.user.username)
        form.instance.save()
        return super(GeneralProgramAuditCreateView, self).form_valid(form)


class GeneralProgramAuditDetailView(ProfileMixin, DetailView):
    template_name = 'audit/general_program_detail.html'
    model = GeneralProgramAudit
    context_object_name = 'general_program'

    def get_context_data(self, **kwargs):
        context = super(GeneralProgramAuditDetailView, self).get_context_data(**kwargs)
        context['audit_list'] = Audit.objects.filter(general_program=self.object)
        return context


class GeneralProgramAuditDeleteView(SuperUserRequiredMixin, DeleteView):
    model = GeneralProgramAudit

    def get_success_url(self):
        return reverse_lazy('audit:list_general_program')


class AuditCreateView(SuperUserRequiredMixin, CreateView):
    model = Audit
    form_class = AuditForm
    success_url = reverse_lazy('audit:list_general_program')

    def form_valid(self, form):
        form.instance.general_program = GeneralProgramAudit.objects.get(pk=self.kwargs['pk'])
        form.instance.save()
        return super(AuditCreateView, self).form_valid(form)


class AuditUpdateView(SuperUserRequiredMixin, UpdateView):
    model = Audit
    form_class = AuditForm

    def get_success_url(self):
        return reverse_lazy('audit:detail_general_program', kwargs={'pk': self.object.general_program.pk})


class AuditDeleteView(SuperUserRequiredMixin, DeleteView):
    model = Audit
    success_url = reverse_lazy('audit:list_general_program')

audit/templates/audit/audit_confirm_delete.html
{% extends 'account/dashboard.html' %}
{% block title %}
    Eliminar Auditoria
{% endblock %}

{% block content-left %}
    <h4>¿Estas seguro de que desea borrar esta auditoria?</h4>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn red">Aceptar</button>
        <a href="{% url 'audit:list_general_program' %}" class="btn blue">Cancelar</a>
    </form>
{% endblock %}

audit/templates/audit/audit_form.html
{% extends 'account/dashboard.html' %}

{% block title %}
    Añadir una auditoria
{% endblock %}

{% block content-left %}
    <form method="post">
        {% csrf_token %}
        {{ form.area.errors }}
        {{ form.area.label_tag }}
        {{ form.area }}
        <table>
            <thead>
                <tr>
                    <th>E</th>
                    <th>F</th>
                    <th>M</th>
                    <th>A</th>
                    <th>M</th>
                    <th>J</th>
                    <th>J</th>
                    <th>A</th>
                    <th>S</th>
                    <th>O</th>
                    <th>N</th>
                    <th>D</th>
                </tr>
            </thead>
            <tbody>
                <td>{{ form.e }}</td>
                <td>{{ form.f }}</td>
                <td>{{ form.ma }}</td>
                <td>{{ form.ab }}</td>
                <td>{{ form.m }}</td>
                <td>{{ form.j }}</td>
                <td>{{ form.ju }}</td>
                <td>{{ form.a }}</td>
                <td>{{ form.s }}</td>
                <td>{{ form.o }}</td>
                <td>{{ form.n }}</td>
                <td>{{ form.d }}</td>
            </tbody>
        </table>
        <button type="submit" class="btn blue">Aceptar</button>
    </form>
{% endblock %}

audit/templates/audit/general_program_detail.html
{% extends 'account/dashboard.html' %}

{% block title %}
    auditorias internas
{% endblock %}

{% block content-left %}
    <div class="col l9">
        <h4 class="center">Registro de Auditorias Internas</h4>
        <h5 class="center">Programa general de auditorias</h5>
    </div>
    <div class="col l3">
        <p>Codigo: {{ general_program.code }}</p>
        <p>Fecha: {{ general_program.date }}</p>
    </div>
    <table>
        <thead>
        <tr>
            <th>Area a auditar</th>
            <th>e</th>
            <th>f</th>
            <th>m</th>
            <th>a</th>
            <th>m</th>
            <th>j</th>
            <th>j</th>
            <th>a</th>
            <th>s</th>
            <th>o</th>
            <th>n</th>
            <th>d</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for audit in audit_list %}
            <tr>
                <td><a href="{% url 'model:detail_area' audit.area.pk %}">{{ audit.area }}</a></td>
                {% if audit.e %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_e_display }}">{{ audit.e }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.f %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_f_display }}">{{ audit.f }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.ma %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_ma_display }}">{{ audit.ma }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.ab %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_ab_display }}">{{ audit.ab }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.m %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_m_display }}">{{ audit.m }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.j %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_j_display }}">{{ audit.j }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.ju %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_ju_display }}">{{ audit.ju }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.a %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_a_display }}">{{ audit.a }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.s %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_s_display }}">{{ audit.s }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.o %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_o_display }}">{{ audit.o }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.n %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_n_display }}">{{ audit.n }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                {% if audit.d %}
                    <td class="tooltipped" data-position="bottom" data-delay="50"
                        data-tooltip="{{ audit.get_d_display }}">{{ audit.d }}</td>
                {% else %}
                    <td></td>
                {% endif %}
                <td>
                    <a href="{% url 'audit:update_audit' audit.pk %}"><i class="material-icons">mode_edit</i></a>
                    <a href="{% url 'audit:delete_audit' audit.pk %}"><i class="material-icons">delete</i></a>
                </td>
                {% empty %}
                <td>No hay auditorias</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h6>Observaciones: {{ general_program.observations }}</h6>
    <h6>Elaborado por: <a href="{% url 'account:detail_user' general_program.made_by.pk %}">{{ general_program.made_by }}</a></h6>
    {% if user.is_superuser %}
        <a href="{% url 'audit:update_general_program' general_program.pk %}" class="btn blue-grey">Editar Programa General</a>
        <a href="{% url 'audit:delete_general_program' general_program.pk %}" class="btn red">Eliminar Programa General</a>
        <a href="{% url 'audit:create_audit' general_program.pk %}" class="btn blue">Añadir auditoria</a>
    {% endif %}
{% endblock %}

audit/templates/audit/general_program_form.html
{% extends 'account/dashboard.html' %}
{% block title %}
    Programa General
{% endblock %}

{% block content-left %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn blue">Aceptar</button>
        <a href="{% url 'audit:list_general_program' %}" class="btn blue-grey">Cancelar</a>
    </form>
{% endblock %}

audit/templates/audit/generalprogramaudit_confirm_delete.html
{% extends 'account/dashboard.html' %}

{% block title %}
    Eliminar Programa General
{% endblock %}

{% block content-left %}
    <h4>¿Desea eliminar programa general?</h4>
    <form method="post">
        <button class="btn red">Aceptar</button>
        <a href="{% url 'audit:detail_general_program' generalprogramaudit.pk %}" class="btn blue">Cancelar</a>
    </form>
{% endblock %}