account/urls.py
from django.conf.urls import url

from account.views import LoginView, LogoutView, ProfileCreateView, ProfileDeleteView, ProfileListView, \
    ProfileUpdateView, ProfileUpdatePasswordView, ProfileDetailView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^create/$', ProfileCreateView.as_view(), name='create_user'),
    url(r'^list/$', ProfileListView.as_view(), name='list_user'),
    url(r'^update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='update_user'),
    url(r'^update/password/(?P<pk>[0-9]+)/$', ProfileUpdatePasswordView.as_view(), name='update_password_user'),
    url(r'^detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='detail_user'),
    url(r'^delete/(?P<pk>[0-9]+)/$', ProfileDeleteView.as_view(), name='delete_user'),
]

airport/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from account.views import DashboardView
from airport import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('account.urls', namespace='account')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^model/', include('model.urls', namespace='model')),
    url(r'^picture/', include('picture.urls', namespace='picture')),
    url(r'^audit/', include('audit.urls', namespace='audit')),
    url(r'^waste/', include('dangerous_waste.urls', namespace='waste')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^bulletin/', include('bulletin.urls', namespace='bulletin')),
    url(r'^training/', include('training.urls', namespace='training')),
    url(r'^environmental/council/', include('environmental_council.urls', namespace='environmental_council')),
    url(r'^bibliography/', include('bibliography.urls', namespace='bibliography')),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

model/urls.py
from django.conf.urls import url

from model.views import ModelR01PG01CreateView, ModelR01PG01UpdateView, ModelR01PG01DetailView, ModelR01PG01ListView, \
    ModelR01PG01DeleteView, AreaCreateView, AreaUpdateView, AreaDetailView, AreaListView, AreaDeleteView, \
    LawRequirementCreateView, LawRequirementDeleteView, LawRequirementDetailView, LawRequirementListView, \
    LawRequirementUpdateView, EmergencyReportCreateView, EmergencyReportDeleteView, EmergencyReportDetailView, \
    EmergencyReportListView, EmergencyReportUpdateView, RealAnalysisCreateView, RealAnalysisDeleteView, \
    RealAnalysisDetailView, RealAnalysisListView, RealAnalysisUpdateView, SimulationAnalysisCreateView, \
    SimulationAnalysisDeleteView, SimulationAnalysisDetailView, SimulationAnalysisListView, \
    SimulationAnalysisUpdateView, CommunicationCreateView, CommunicationDeleteView, CommunicationDetailView, \
    CommunicationListView, CommunicationUpdateView, ModelR01PG01ListAllView, EnvironmentalMatrixCreateView, \
    EnvironmentalMatrixUpdateView, EnvironmentalMatrixDetailView, EnvironmentalMatrixDeleteView, \
    EnvironmentalMatrixListView

urlpatterns = [
    url(r'^create/r01pg01/$', ModelR01PG01CreateView.as_view(), name='create_modelr01pg01'),
    url(r'^update/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01UpdateView.as_view(), name='update_modelr01pg01'),
    url(r'^detail/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DetailView.as_view(), name='detail_modelr01pg01'),
    url(r'^list/r01pg01/$', ModelR01PG01ListView.as_view(), name='list_modelr01pg01'),
    url(r'^list/all/r01pg01/$', ModelR01PG01ListAllView.as_view(), name='list_all_modelr01pg01'),
    url(r'^delete/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DeleteView.as_view(), name='delete_modelr01pg01'),

    url(r'^create/area/$', AreaCreateView.as_view(), name='create_area'),
    url(r'^update/area/(?P<pk>[0-9]+)/$', AreaUpdateView.as_view(), name='update_area'),
    url(r'^detail/area/(?P<pk>[0-9]+)/$', AreaDetailView.as_view(), name='detail_area'),
    url(r'^list/area/$', AreaListView.as_view(), name='list_area'),
    url(r'^delete/area/(?P<pk>[0-9]+)/$', AreaDeleteView.as_view(), name='delete_area'),

    url(r'^create/law/$', LawRequirementCreateView.as_view(), name='create_law'),
    url(r'^update/law/(?P<pk>[0-9]+)/$', LawRequirementUpdateView.as_view(), name='update_law'),
    url(r'^detail/law/(?P<pk>[0-9]+)/$', LawRequirementDetailView.as_view(), name='detail_law'),
    url(r'^list/law/$', LawRequirementListView.as_view(), name='list_law'),
    url(r'^delete/law/(?P<pk>[0-9]+)/$', LawRequirementDeleteView.as_view(), name='delete_law'),

    url(r'^create/emergency/$', EmergencyReportCreateView.as_view(), name='create_emergency'),
    url(r'^update/emergency/(?P<pk>[0-9]+)/$', EmergencyReportUpdateView.as_view(), name='update_emergency'),
    url(r'^detail/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDetailView.as_view(), name='detail_emergency'),
    url(r'^list/emergency/$', EmergencyReportListView.as_view(), name='list_emergency'),
    url(r'^delete/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDeleteView.as_view(), name='delete_emergency'),

    url(r'^create/real/analysis/$', RealAnalysisCreateView.as_view(), name='create_real_analysis'),
    url(r'^update/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisUpdateView.as_view(), name='update_real_analysis'),
    url(r'^detail/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDetailView.as_view(), name='detail_real_analysis'),
    url(r'^list/real/analysis/$', RealAnalysisListView.as_view(), name='list_real_analysis'),
    url(r'^delete/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDeleteView.as_view(), name='delete_real_analysis'),

    url(r'^create/simulation/analysis/$', SimulationAnalysisCreateView.as_view(), name='create_simulation_analysis'),
    url(r'^update/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisUpdateView.as_view(),
        name='update_simulation_analysis'),
    url(r'^detail/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDetailView.as_view(),
        name='detail_simulation_analysis'),
    url(r'^list/simulation/analysis/$', SimulationAnalysisListView.as_view(), name='list_simulation_analysis'),
    url(r'^delete/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDeleteView.as_view(),
        name='delete_simulation_analysis'),

    url(r'^create/communication/$', CommunicationCreateView.as_view(), name='create_communication'),
    url(r'^update/communication/(?P<pk>[0-9]+)/$', CommunicationUpdateView.as_view(), name='update_communication'),
    url(r'^detail/communication/(?P<pk>[0-9]+)/$', CommunicationDetailView.as_view(), name='detail_communication'),
    url(r'^list/communication/$', CommunicationListView.as_view(), name='list_communication'),
    url(r'^delete/communication/(?P<pk>[0-9]+)/$', CommunicationDeleteView.as_view(), name='delete_communication'),

    url(r'^create/environmental/matrix/$', EnvironmentalMatrixCreateView.as_view(),
        name='create_environmental_matrix'),
    url(r'^list/environmental/matrix/$', EnvironmentalMatrixListView.as_view(),
        name='list_environmental_matrix'),
    url(r'^update/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixUpdateView.as_view(),
        name='update_environmental_matrix'),
    url(r'^detail/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDetailView.as_view(),
        name='detail_environmental_matrix'),
    url(r'^delete/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDeleteView.as_view(),
        name='delete_environmental_matrix'),

]

poll/urls.py
from django.conf.urls import url

from poll.views import NationalPassengerPollCreateView, NationalPassengerPollListView, \
    NationalPassengerPollUpdateView, NationalPassengerPollDetailView, \
    NationalPassengerPollDeleteView, AllPollView, InternationalPassengerPollCreateView, \
    InternationalPassengerPollListView, InternationalPassengerPollUpdateView, InternationalPassengerPollDetailView, \
    InternationalPassengerPollDeleteView, AirLineRepresentPollCreateView, AirLineRepresentPollListView, \
    AirLineRepresentPollUpdateView, AirLineRepresentPollDetailView, AirLineRepresentPollDeleteView

urlpatterns = [
    url(r'international/passenger/create/$', InternationalPassengerPollCreateView.as_view(),
        name='create_international_passenger'),
    url(r'international/passenger/list/$', InternationalPassengerPollListView.as_view(),
        name='list_international_passenger'),
    url(r'international/passenger/update/(?P<pk>[0-9]+)/$', InternationalPassengerPollUpdateView.as_view(),
        name='update_international_passenger'),
    url(r'international/passenger/detail/(?P<pk>[0-9]+)/$', InternationalPassengerPollDetailView.as_view(),
        name='detail_international_passenger'),
    url(r'international/passenger/delete/(?P<pk>[0-9]+)/$', InternationalPassengerPollDeleteView.as_view(),
        name='delete_international_passenger'),

    url(r'national/passenger/create/$', NationalPassengerPollCreateView.as_view(),
        name='create_national_passenger'),
    url(r'national/passenger/list/$', NationalPassengerPollListView.as_view(),
        name='list_national_passenger'),
    url(r'national/passenger/update/(?P<pk>[0-9]+)/$', NationalPassengerPollUpdateView.as_view(),
        name='update_national_passenger'),
    url(r'national/passenger/detail/(?P<pk>[0-9]+)/$', NationalPassengerPollDetailView.as_view(),
        name='detail_national_passenger'),
    url(r'national/passenger/delete/(?P<pk>[0-9]+)/$', NationalPassengerPollDeleteView.as_view(),
        name='delete_national_passenger'),

    url(r'airline/represent/create/$', AirLineRepresentPollCreateView.as_view(),
        name='create_airline_represent'),
    url(r'airline/represent/list/$', AirLineRepresentPollListView.as_view(),
        name='list_airline_represent'),
    url(r'airline/represent/update/(?P<pk>[0-9]+)/$', AirLineRepresentPollUpdateView.as_view(),
        name='update_airline_represent'),
    url(r'airline/represent/detail/(?P<pk>[0-9]+)/$', AirLineRepresentPollDetailView.as_view(),
        name='detail_airline_represent'),
    url(r'airline/represent/delete/(?P<pk>[0-9]+)/$', AirLineRepresentPollDeleteView.as_view(),
        name='delete_airline_represent'),

    url(r'all/$', AllPollView.as_view(), name='all_poll'),
]

account/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

SEX_CHOICES = (
    ('M', 'Masculino'),
    ('W', 'Femenino'),
    ('U', 'Sin definir'),
)


def url(self, filename):
    route = 'users/{}/{}'.format(self.username, filename)
    return route


class Profile(User):
    picture = models.ImageField('Imagen', blank=True, null=True, upload_to=url)
    born_date = models.DateField('Fecha de nacimiento', blank=True, null=True)
    gender = models.CharField('Genero', max_length=1, choices=SEX_CHOICES, default='U')
    area = models.ForeignKey('model.Area')

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def age(self):
        actual = timezone.now().year
        born_year = self.born_date.year
        return actual - born_year

    def set_picture(self, picture):
        self.picture = picture

    def __str__(self):
        return self.get_full_name()

audit/models.py
from django.core.exceptions import ValidationError
from django.db import models

from account.models import Profile
from model.models import Area

AUDIT_TYPE = (
    ('nc', 'Auditoría Nivel Central'),
    ('sgc', 'Auditoría al SGC'),
    ('z', 'Auditoría de la UEB Aeropuerto'),
    ('sga', 'Auditoría al SGA'),
    ('e', 'Auditoría de la Especialidad (UEB Nacionales)'),
    ('sgi', 'Auditoría al SGICH'),
    ('bv', 'Auditoría de Bureau Veritas'),
    ('ai', 'Auditoría Integrada'),
)


def validate_month(value):
    if value > 12 or value < 1:
        raise ValidationError(
            '%(value)s no es un mes válido. NOTA: el mes debe estar entre 1 y 12',
            params={'value': value},
        )


MONTH = {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre',
}


class GeneralProgramAudit(models.Model):
    code = 'R-01/PG.01-05'
    # audit = models.ForeignKey(Audit, verbose_name='Auditoria')
    observations = models.TextField('Observaciones')
    made_by = models.ForeignKey(Profile, verbose_name='Elaborado por')
    date = models.DateField('Fecha', auto_now=True)

    class Meta:
        verbose_name = 'Programa General'
        verbose_name_plural = 'Programas Generales'

    def __str__(self):
        return '{} {}'.format(self.code, self.observations)


class Audit(models.Model):
    area = models.ForeignKey(Area, verbose_name='Area')
    general_program = models.ForeignKey(GeneralProgramAudit, verbose_name='Programa general')
    e = models.CharField('Enero', choices=AUDIT_TYPE, blank=True, max_length=3)
    f = models.CharField('Febrero', choices=AUDIT_TYPE, blank=True, max_length=3)
    ma = models.CharField('Marzo', choices=AUDIT_TYPE, blank=True, max_length=3)
    ab = models.CharField('Abril', choices=AUDIT_TYPE, blank=True, max_length=3)
    m = models.CharField('Mayo', choices=AUDIT_TYPE, blank=True, max_length=3)
    j = models.CharField('Junio', choices=AUDIT_TYPE, blank=True, max_length=3)
    ju = models.CharField('Julio', choices=AUDIT_TYPE, blank=True, max_length=3)
    a = models.CharField('Agosto', choices=AUDIT_TYPE, blank=True, max_length=3)
    s = models.CharField('Septiembre', choices=AUDIT_TYPE, blank=True, max_length=3)
    o = models.CharField('Octubre', choices=AUDIT_TYPE, blank=True, max_length=3)
    n = models.CharField('Noviembre', choices=AUDIT_TYPE, blank=True, max_length=3)
    d = models.CharField('Diciembre', choices=AUDIT_TYPE, blank=True, max_length=3)

    class Meta:
        verbose_name = 'Auditoria'
        verbose_name_plural = 'Auditorias'

    def __str__(self):
        return '{} {}'.format(self.area, self.general_program)


class AuditPlan(models.Model):
    code = 'R-02/PG.01-05'
    pass


class VerifyList(models.Model):
    code = 'R-03/PG.01-05'
    pass


class AuditInform(models.Model):
    code = 'R-04/PG.01-05'
    pass


class AuditControl(models.Model):
    code = 'R-05/PG.01-05'
    pass

bibliography/models.py
from django.db import models

DOCUMENT_TYPE_CHOICES = (
    ('CGA', 'Consejo de Gestion Ambiental'),
    ('Otros', 'Otros Documentos'),
)


class Bibliography(models.Model):
    document_type = models.CharField('Tipo de documento', max_length=5, choices=DOCUMENT_TYPE_CHOICES)
    pub_date = models.DateField(auto_now=True)
    file = models.FileField('Fichero')

    class Meta:
        verbose_name = 'Bibliografia'
        verbose_name_plural = 'Bibliografias'

    def __str__(self):
        return '{} {}'.format(self.document_type, self.file)

bulletin/models.py
from django.db import models


class Bulletin(models.Model):
    title = models.CharField('Titulo', max_length=150)
    file = models.FileField('PDF')
    pub_date = models.DateField('Fecha de Publicacion', auto_now=True)

    class Meta:
        verbose_name = 'Boletin'
        verbose_name_plural = 'Boletines'

    def __str__(self):
        return '{} {}'.format(self.title, self.pub_date)

environmental_council/models.py
from django.db import models


class EnvironmentalCouncil(models.Model):
    first_name = models.CharField('Nombre', max_length=100)
    last_name = models.CharField('Apellidos', max_length=200)
    position = models.CharField('Cargo', max_length=150)

    class Meta:
        verbose_name = 'Integrante del Consejo Ambiental'
        verbose_name_plural = 'Integrantes del Consejo Ambiental'

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return self.get_full_name()

event/models.py
from django.db import models


class Event(models.Model):
    date = models.DateField('Fecha')
    title = models.CharField('Título', max_length=100)
    description = models.TextField('Descripción', blank=True, null=True)

    class Meta:
        verbose_name = 'Efeméride'
        verbose_name_plural = 'Efemérides'

    def __str__(self):
        return "{} -> {}".format(self.date, self.title)

model/forms.py
from django import forms

from model.models import EmergencyReport, SimulationAnalysis, Communication


class EmergencyReportCreateForm(forms.ModelForm):
    class Meta:
        model = EmergencyReport
        fields = ['no', 'report', 'datetime', 'place', 'description']
        # widgets = {
        #     'datetime': forms.DateTimeInput(attrs={'class': 'datepicker'})
        # }


class SimulationAnalysisCreateForm(forms.ModelForm):
    class Meta:
        model = SimulationAnalysis
        fields = ['summary', 'evaluation', 'is_necessary_check', 'specify', 'emergency', 'participants']
        # widgets = {
        #     'emergency': forms.ModelChoiceField(
        #         queryset=EmergencyReport.objects.filter(report__contains='s')
        #     )
        # }


class CommunicationForm(forms.ModelForm):
    class Meta:
        model = Communication
        fields = ['airport_name', 'year', 'reception_way', 'type_communication', 'contact_data', 'info_content',
                  'adopted_decision', 'distribution_date', 'emission_path']
        widgets = {
            'distribution_date': forms.DateInput(attrs={'class': 'datepicker'})
        }

model/templates/law_requirements/lawrequirement_confirm_delete.html
{% extends 'account/dashboard.html' %}

{% block title %}
Eliminar {{ law.law }}
{% endblock %}

{% block content-left %}
    <h3>¿Estas seguro de que deseas borrar esta ley?</h3>
    <form method="post">
    {% csrf_token %}
        <input type="submit" class="btn red" value="Aceptar">
    </form>
{% endblock %}

model/templates/law_requirements/lawrequirement_detail.html
{% extends 'account/dashboard.html' %}

{% block title %}
    {{ lawrequirement.law }}
{% endblock %}

{% block content-left %}
    <h6><strong>Requerimientos:</strong> {{ lawrequirement.requirements }}</h6>
    <h6><strong>Ley:</strong> {{ lawrequirement.law }}</h6>
    <p><strong>Seccion:</strong> {{ lawrequirement.section }}</p>
    <p><strong>Aspectos ambientales:</strong> {{ lawrequirement.environmental_aspects }}</p>
    <p><strong>Creado por:</strong> <a href="{% url 'account:detail_user' lawrequirement.register_by.pk %}">{{ lawrequirement.register_by }}</a></p>
    <p><strong>Fecha de publicacion:</strong> {{ lawrequirement.pub_date }}</p>
    {% if lawrequirement.file %}
        <p>
            <a href="{{ lawrequirement.file.url }}" class="btn blue-grey tooltipped"
               data-position="right" data-delay="50" data-tooltip="Descargar documento">
                Documento
                <i class="material-icons right">system_update_alt</i>
            </a>
        </p>
    {% endif %}
    <a href="{% url 'model:list_law' %}" class="btn blue">Listado de leyes</a>
{% endblock %}

model/templates/law_requirements/lawrequirement_form.html
{% extends 'account/dashboard.html' %}

{% block title %}
    Requerimientos legales
{% endblock %}

{% block content-left %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Aceptar" class="btn blue">
    </form>
{% endblock %}

model/templates/law_requirements/lawrequirement_list.html
{% extends 'account/dashboard.html' %}

{% block title %}
    Todas las leyes
{% endblock %}

{% block content-left %}
    <table class="table">
        <thead>
        <tr>
            <th>No</th>
            <th>Ley</th>
            <th>Registrado por</th>
            <th>Fecha de publicacion</th>
            <th>Documento</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for law in laws %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="#law{{ forloop.counter }}" class="modal-trigger">{{ law.law }}</a></td>
                <td><a href="{% url 'account:detail_user' law.register_by.pk %}">{{ law.register_by }}</a></td>
                <td>{{ law.pub_date }}</td>
                {% if law.file %}
                    <td>
                        <a href="{{ law.file.url }}" class="btn-floating btn-sm waves-effect waves-light blue tooltipped"
                           data-position="bottom" data-delay="50" data-tooltip="Descargar documento">
                            <i class="material-icons">system_update_alt</i>
                        </a>
                    </td>
                {% else %}
                    <td>No hay documento</td>
                {% endif %}
                <td colspan="3">
                    <a href="{% url 'model:detail_law' law.pk %}"><i class="material-icons">description</i></a>
                    {% if user.is_superuser %}
                        <a href="{% url 'model:update_law' law.pk %}"><i class="material-icons">edit_mode</i></a>
                        <a href="{% url 'model:delete_law' law.pk %}"><i class="material-icons">delete</i></a>
                    {% endif %}
                </td>
            </tr>
        {% empty %}
            <h5 class="center">No se han subido leyes todavía</h5>
        {% endfor %}
        </tbody>
    </table>
    {% for law in laws %}
        <div id="law{{ forloop.counter }}" class="modal modal-fixed-footer">
            <div class="modal-content">
                <h4>{{ law.code }} {{ law.law }}</h4>
                <p><strong>Requerimientos:</strong> {{ law.requirements }}</p>
                <p><strong>Seccion:</strong> {{ law.section }}</p>
                <p><strong>Aspectos Ambientales:</strong> {{ law.environmental_aspects }}</p>
                <p><strong>Creado por:</strong> {{ law.register_by }}</p>
                <p><strong>Fecha de publicacion:</strong> {{ law.pub_date }}</p>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-action modal-close waves-effect blue btn-flat">Cerrar</a>
            </div>
        </div>
    {% endfor %}
    {% if user.is_superuser %}
        <a href="{% url 'model:create_law' %}" class="btn blue">Añadir Ley</a>
    {% endif %}
{% endblock %}