account/urls.py
from django.conf.urls import url

from account.views import LoginView, LogoutView, ProfileCreateView, ProfileDeleteView, ProfileListView, \
    ProfileUpdateView, ProfileUpdatePasswordView, ProfileDetailView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^create/$', ProfileCreateView.as_view(), name='create_user'),
    url(r'^list/$', ProfileListView.as_view(), name='list_user'),
    url(r'^update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='update_user'),
    url(r'^update/password/(?P<pk>[0-9]+)/$', ProfileUpdatePasswordView.as_view(), name='update_password_user'),
    url(r'^detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='detail_user'),
    url(r'^delete/(?P<pk>[0-9]+)/$', ProfileDeleteView.as_view(), name='delete_user'),
]

airport/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from account.views import DashboardView
from airport import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('account.urls', namespace='account')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^model/', include('model.urls', namespace='model')),
    url(r'^picture/', include('picture.urls', namespace='picture')),
    url(r'^audit/', include('audit.urls', namespace='audit')),
    url(r'^waste/', include('dangerous_waste.urls', namespace='waste')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^bulletin/', include('bulletin.urls', namespace='bulletin')),
    url(r'^training/', include('training.urls', namespace='training')),
    url(r'^environmental/council/', include('environmental_council.urls', namespace='environmental_council')),
    url(r'^bibliography/', include('bibliography.urls', namespace='bibliography')),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

model/urls.py
from django.conf.urls import url

from model.views import ModelR01PG01CreateView, ModelR01PG01UpdateView, ModelR01PG01DetailView, ModelR01PG01ListView, \
    ModelR01PG01DeleteView, AreaCreateView, AreaUpdateView, AreaDetailView, AreaListView, AreaDeleteView, \
    LawRequirementCreateView, LawRequirementDeleteView, LawRequirementDetailView, LawRequirementListView, \
    LawRequirementUpdateView, EmergencyReportCreateView, EmergencyReportDeleteView, EmergencyReportDetailView, \
    EmergencyReportListView, EmergencyReportUpdateView, RealAnalysisCreateView, RealAnalysisDeleteView, \
    RealAnalysisDetailView, RealAnalysisListView, RealAnalysisUpdateView, SimulationAnalysisCreateView, \
    SimulationAnalysisDeleteView, SimulationAnalysisDetailView, SimulationAnalysisListView, \
    SimulationAnalysisUpdateView, CommunicationCreateView, CommunicationDeleteView, CommunicationDetailView, \
    CommunicationListView, CommunicationUpdateView, ModelR01PG01ListAllView, EnvironmentalMatrixCreateView, \
    EnvironmentalMatrixUpdateView, EnvironmentalMatrixDetailView, EnvironmentalMatrixDeleteView, \
    EnvironmentalMatrixListView

urlpatterns = [
    url(r'^create/r01pg01/$', ModelR01PG01CreateView.as_view(), name='create_modelr01pg01'),
    url(r'^update/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01UpdateView.as_view(), name='update_modelr01pg01'),
    url(r'^detail/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DetailView.as_view(), name='detail_modelr01pg01'),
    url(r'^list/r01pg01/$', ModelR01PG01ListView.as_view(), name='list_modelr01pg01'),
    url(r'^list/all/r01pg01/$', ModelR01PG01ListAllView.as_view(), name='list_all_modelr01pg01'),
    url(r'^delete/r01pg01/(?P<pk>[0-9]+)/$', ModelR01PG01DeleteView.as_view(), name='delete_modelr01pg01'),

    url(r'^create/area/$', AreaCreateView.as_view(), name='create_area'),
    url(r'^update/area/(?P<pk>[0-9]+)/$', AreaUpdateView.as_view(), name='update_area'),
    url(r'^detail/area/(?P<pk>[0-9]+)/$', AreaDetailView.as_view(), name='detail_area'),
    url(r'^list/area/$', AreaListView.as_view(), name='list_area'),
    url(r'^delete/area/(?P<pk>[0-9]+)/$', AreaDeleteView.as_view(), name='delete_area'),

    url(r'^create/law/$', LawRequirementCreateView.as_view(), name='create_law'),
    url(r'^update/law/(?P<pk>[0-9]+)/$', LawRequirementUpdateView.as_view(), name='update_law'),
    url(r'^detail/law/(?P<pk>[0-9]+)/$', LawRequirementDetailView.as_view(), name='detail_law'),
    url(r'^list/law/$', LawRequirementListView.as_view(), name='list_law'),
    url(r'^delete/law/(?P<pk>[0-9]+)/$', LawRequirementDeleteView.as_view(), name='delete_law'),

    url(r'^create/emergency/$', EmergencyReportCreateView.as_view(), name='create_emergency'),
    url(r'^update/emergency/(?P<pk>[0-9]+)/$', EmergencyReportUpdateView.as_view(), name='update_emergency'),
    url(r'^detail/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDetailView.as_view(), name='detail_emergency'),
    url(r'^list/emergency/$', EmergencyReportListView.as_view(), name='list_emergency'),
    url(r'^delete/emergency/(?P<pk>[0-9]+)/$', EmergencyReportDeleteView.as_view(), name='delete_emergency'),

    url(r'^create/real/analysis/$', RealAnalysisCreateView.as_view(), name='create_real_analysis'),
    url(r'^update/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisUpdateView.as_view(), name='update_real_analysis'),
    url(r'^detail/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDetailView.as_view(), name='detail_real_analysis'),
    url(r'^list/real/analysis/$', RealAnalysisListView.as_view(), name='list_real_analysis'),
    url(r'^delete/real/analysis/(?P<pk>[0-9]+)/$', RealAnalysisDeleteView.as_view(), name='delete_real_analysis'),

    url(r'^create/simulation/analysis/$', SimulationAnalysisCreateView.as_view(), name='create_simulation_analysis'),
    url(r'^update/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisUpdateView.as_view(),
        name='update_simulation_analysis'),
    url(r'^detail/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDetailView.as_view(),
        name='detail_simulation_analysis'),
    url(r'^list/simulation/analysis/$', SimulationAnalysisListView.as_view(), name='list_simulation_analysis'),
    url(r'^delete/simulation/analysis/(?P<pk>[0-9]+)/$', SimulationAnalysisDeleteView.as_view(),
        name='delete_simulation_analysis'),

    url(r'^create/communication/$', CommunicationCreateView.as_view(), name='create_communication'),
    url(r'^update/communication/(?P<pk>[0-9]+)/$', CommunicationUpdateView.as_view(), name='update_communication'),
    url(r'^detail/communication/(?P<pk>[0-9]+)/$', CommunicationDetailView.as_view(), name='detail_communication'),
    url(r'^list/communication/$', CommunicationListView.as_view(), name='list_communication'),
    url(r'^delete/communication/(?P<pk>[0-9]+)/$', CommunicationDeleteView.as_view(), name='delete_communication'),

    url(r'^create/environmental/matrix/$', EnvironmentalMatrixCreateView.as_view(),
        name='create_environmental_matrix'),
    url(r'^list/environmental/matrix/$', EnvironmentalMatrixListView.as_view(),
        name='list_environmental_matrix'),
    url(r'^update/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixUpdateView.as_view(),
        name='update_environmental_matrix'),
    url(r'^detail/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDetailView.as_view(),
        name='detail_environmental_matrix'),
    url(r'^delete/environmental/matrix/(?P<pk>[0-9]+)/$', EnvironmentalMatrixDeleteView.as_view(),
        name='delete_environmental_matrix'),

]

poll/urls.py
from django.conf.urls import url

from poll.views import NationalPassengerPollCreateView, NationalPassengerPollListView, \
    NationalPassengerPollUpdateView, NationalPassengerPollDetailView, \
    NationalPassengerPollDeleteView, AllPollView, InternationalPassengerPollCreateView, \
    InternationalPassengerPollListView, InternationalPassengerPollUpdateView, InternationalPassengerPollDetailView, \
    InternationalPassengerPollDeleteView, AirLineRepresentPollCreateView, AirLineRepresentPollListView, \
    AirLineRepresentPollUpdateView, AirLineRepresentPollDetailView, AirLineRepresentPollDeleteView

urlpatterns = [
    url(r'international/passenger/create/$', InternationalPassengerPollCreateView.as_view(),
        name='create_international_passenger'),
    url(r'international/passenger/list/$', InternationalPassengerPollListView.as_view(),
        name='list_international_passenger'),
    url(r'international/passenger/update/(?P<pk>[0-9]+)/$', InternationalPassengerPollUpdateView.as_view(),
        name='update_international_passenger'),
    url(r'international/passenger/detail/(?P<pk>[0-9]+)/$', InternationalPassengerPollDetailView.as_view(),
        name='detail_international_passenger'),
    url(r'international/passenger/delete/(?P<pk>[0-9]+)/$', InternationalPassengerPollDeleteView.as_view(),
        name='delete_international_passenger'),

    url(r'national/passenger/create/$', NationalPassengerPollCreateView.as_view(),
        name='create_national_passenger'),
    url(r'national/passenger/list/$', NationalPassengerPollListView.as_view(),
        name='list_national_passenger'),
    url(r'national/passenger/update/(?P<pk>[0-9]+)/$', NationalPassengerPollUpdateView.as_view(),
        name='update_national_passenger'),
    url(r'national/passenger/detail/(?P<pk>[0-9]+)/$', NationalPassengerPollDetailView.as_view(),
        name='detail_national_passenger'),
    url(r'national/passenger/delete/(?P<pk>[0-9]+)/$', NationalPassengerPollDeleteView.as_view(),
        name='delete_national_passenger'),

    url(r'airline/represent/create/$', AirLineRepresentPollCreateView.as_view(),
        name='create_airline_represent'),
    url(r'airline/represent/list/$', AirLineRepresentPollListView.as_view(),
        name='list_airline_represent'),
    url(r'airline/represent/update/(?P<pk>[0-9]+)/$', AirLineRepresentPollUpdateView.as_view(),
        name='update_airline_represent'),
    url(r'airline/represent/detail/(?P<pk>[0-9]+)/$', AirLineRepresentPollDetailView.as_view(),
        name='detail_airline_represent'),
    url(r'airline/represent/delete/(?P<pk>[0-9]+)/$', AirLineRepresentPollDeleteView.as_view(),
        name='delete_airline_represent'),

    url(r'all/$', AllPollView.as_view(), name='all_poll'),
]

account/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

SEX_CHOICES = (
    ('M', 'Masculino'),
    ('W', 'Femenino'),
    ('U', 'Sin definir'),
)


def url(self, filename):
    route = 'users/{}/{}'.format(self.username, filename)
    return route


class Profile(User):
    picture = models.ImageField('Imagen', blank=True, null=True, upload_to=url)
    born_date = models.DateField('Fecha de nacimiento', blank=True, null=True)
    gender = models.CharField('Genero', max_length=1, choices=SEX_CHOICES, default='U')
    area = models.ForeignKey('model.Area')

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def age(self):
        actual = timezone.now().year
        born_year = self.born_date.year
        return actual - born_year

    def set_picture(self, picture):
        self.picture = picture

    def __str__(self):
        return self.get_full_name()

audit/models.py
from django.core.exceptions import ValidationError
from django.db import models

from account.models import Profile
from model.models import Area

AUDIT_TYPE = (
    ('nc', 'Auditoría Nivel Central'),
    ('sgc', 'Auditoría al SGC'),
    ('z', 'Auditoría de la UEB Aeropuerto'),
    ('sga', 'Auditoría al SGA'),
    ('e', 'Auditoría de la Especialidad (UEB Nacionales)'),
    ('sgi', 'Auditoría al SGICH'),
    ('bv', 'Auditoría de Bureau Veritas'),
    ('ai', 'Auditoría Integrada'),
)


def validate_month(value):
    if value > 12 or value < 1:
        raise ValidationError(
            '%(value)s no es un mes válido. NOTA: el mes debe estar entre 1 y 12',
            params={'value': value},
        )


MONTH = {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre',
}


class GeneralProgramAudit(models.Model):
    code = 'R-01/PG.01-05'
    # audit = models.ForeignKey(Audit, verbose_name='Auditoria')
    observations = models.TextField('Observaciones')
    made_by = models.ForeignKey(Profile, verbose_name='Elaborado por')
    date = models.DateField('Fecha', auto_now=True)

    class Meta:
        verbose_name = 'Programa General'
        verbose_name_plural = 'Programas Generales'

    def __str__(self):
        return '{} {}'.format(self.code, self.observations)


class Audit(models.Model):
    area = models.ForeignKey(Area, verbose_name='Area')
    general_program = models.ForeignKey(GeneralProgramAudit, verbose_name='Programa general')
    e = models.CharField('Enero', choices=AUDIT_TYPE, blank=True, max_length=3)
    f = models.CharField('Febrero', choices=AUDIT_TYPE, blank=True, max_length=3)
    ma = models.CharField('Marzo', choices=AUDIT_TYPE, blank=True, max_length=3)
    ab = models.CharField('Abril', choices=AUDIT_TYPE, blank=True, max_length=3)
    m = models.CharField('Mayo', choices=AUDIT_TYPE, blank=True, max_length=3)
    j = models.CharField('Junio', choices=AUDIT_TYPE, blank=True, max_length=3)
    ju = models.CharField('Julio', choices=AUDIT_TYPE, blank=True, max_length=3)
    a = models.CharField('Agosto', choices=AUDIT_TYPE, blank=True, max_length=3)
    s = models.CharField('Septiembre', choices=AUDIT_TYPE, blank=True, max_length=3)
    o = models.CharField('Octubre', choices=AUDIT_TYPE, blank=True, max_length=3)
    n = models.CharField('Noviembre', choices=AUDIT_TYPE, blank=True, max_length=3)
    d = models.CharField('Diciembre', choices=AUDIT_TYPE, blank=True, max_length=3)

    class Meta:
        verbose_name = 'Auditoria'
        verbose_name_plural = 'Auditorias'

    def __str__(self):
        return '{} {}'.format(self.area, self.general_program)


class AuditPlan(models.Model):
    code = 'R-02/PG.01-05'
    pass


class VerifyList(models.Model):
    code = 'R-03/PG.01-05'
    pass


class AuditInform(models.Model):
    code = 'R-04/PG.01-05'
    pass


class AuditControl(models.Model):
    code = 'R-05/PG.01-05'
    pass

bibliography/models.py
from django.db import models

DOCUMENT_TYPE_CHOICES = (
    ('CGA', 'Consejo de Gestion Ambiental'),
    ('Otros', 'Otros Documentos'),
)


class Bibliography(models.Model):
    document_type = models.CharField('Tipo de documento', max_length=5, choices=DOCUMENT_TYPE_CHOICES)
    pub_date = models.DateField(auto_now=True)
    file = models.FileField('Fichero')

    class Meta:
        verbose_name = 'Bibliografia'
        verbose_name_plural = 'Bibliografias'

    def __str__(self):
        return '{} {}'.format(self.document_type, self.file)

bulletin/models.py
from django.db import models


class Bulletin(models.Model):
    title = models.CharField('Titulo', max_length=150)
    file = models.FileField('PDF')
    pub_date = models.DateField('Fecha de Publicacion', auto_now=True)

    class Meta:
        verbose_name = 'Boletin'
        verbose_name_plural = 'Boletines'

    def __str__(self):
        return '{} {}'.format(self.title, self.pub_date)

environmental_council/models.py
from django.db import models


class EnvironmentalCouncil(models.Model):
    first_name = models.CharField('Nombre', max_length=100)
    last_name = models.CharField('Apellidos', max_length=200)
    position = models.CharField('Cargo', max_length=150)

    class Meta:
        verbose_name = 'Integrante del Consejo Ambiental'
        verbose_name_plural = 'Integrantes del Consejo Ambiental'

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return self.get_full_name()

event/models.py
from django.db import models


class Event(models.Model):
    date = models.DateField('Fecha')
    title = models.CharField('Título', max_length=100)
    description = models.TextField('Descripción', blank=True, null=True)

    class Meta:
        verbose_name = 'Efeméride'
        verbose_name_plural = 'Efemérides'

    def __str__(self):
        return "{} -> {}".format(self.date, self.title)

model/forms.py
from django import forms

from model.models import EmergencyReport, SimulationAnalysis, Communication


class EmergencyReportCreateForm(forms.ModelForm):
    class Meta:
        model = EmergencyReport
        fields = ['no', 'report', 'datetime', 'place', 'description']
        # widgets = {
        #     'datetime': forms.DateTimeInput(attrs={'class': 'datepicker'})
        # }


class SimulationAnalysisCreateForm(forms.ModelForm):
    class Meta:
        model = SimulationAnalysis
        fields = ['summary', 'evaluation', 'is_necessary_check', 'specify', 'emergency', 'participants']
        # widgets = {
        #     'emergency': forms.ModelChoiceField(
        #         queryset=EmergencyReport.objects.filter(report__contains='s')
        #     )
        # }


class CommunicationForm(forms.ModelForm):
    class Meta:
        model = Communication
        fields = ['airport_name', 'year', 'reception_way', 'type_communication', 'contact_data', 'info_content',
                  'adopted_decision', 'distribution_date', 'emission_path']
        widgets = {
            'distribution_date': forms.DateInput(attrs={'class': 'datepicker'})
        }

model/templates/model/area_confirm_delete.html
{% extends 'account/dashboard.html' %}

{% block title %}
Eliminar area
{% endblock %}

{% block content-left %}
    <h3>Estas seguro de que desea eliminar el area "{{ area.name }}"</h3>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'model:detail_area' area.pk %}" class="btn blue">Cancelar</a>
        <input type="submit" value="Eliminar" class="btn red">
    </form>
{% endblock %}

model/templates/model/area_detail.html
{% extends 'account/dashboard.html' %}

{% block title %}
    Area {{ area.name }}
{% endblock %}

{% block content-left %}
    <h4 class="center">Area {{ area.name }}</h4>
    <div class="col l6">
            <h5>Usuarios</h5>
        {% for profile in area.profile_set.all %}
            <p><a href="{% url 'account:detail_user' profile.pk %}">{{ profile.get_full_name }}</a></p>
        {% endfor %}
    </div>
    <div class="col l6">

    </div>
{% endblock %}

model/templates/model/area_form.html
{% extends 'account/dashboard.html' %}

{% block title %}
Area
{% endblock %}

{% block content-left %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Aceptar" class="btn blue">
    </form>
{% endblock %}

model/templates/model/area_list.html
{% extends 'account/dashboard.html' %}

{% block title %}
Listado de Areas
{% endblock %}

{% block content-left %}
    {% for area in area_list %}
        <p><a href="{% url 'model:detail_area' area.pk %}">{{ area.name }}</a></p>
    {% endfor %}
{% endblock %}

model/templates/model/modelr01pg01_confirm_delete.html
{% extends 'account/dashboard.html' %}

{% block content-down %}
    <h2>¿Estás seguro de querer borrar el modelo?</h2>
    <h4>Area: {{ model.area }}</h4>
    <h4>Año: {{ model.year }}</h4>
    <h4>Aspectos Ambientales: {{ model.environmental_aspects }}</h4>
    <h4>Registrado por: {{ model.register_by }}</h4>
    <h4>Fecha de publicación: {{ model.pub_date }}</h4>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Aceptar" class="btn red">
        <a href="{% url 'model:detail_modelr01pg01' model.pk %}" class="btn blue">Cancelar</a>
    </form>
{% endblock %}

model/templates/model/modelr01pg01_detail.html
{% extends 'account/dashboard.html' %}

{% block content-left %}
    <p>Area: {{ model.area }}</p>
    <p>Año: {{ model.year }}</p>
    <p>Aspectos Ambientales: {{ model.environmental_aspects }}</p>
    <p>Registrado por: {{ model.register_by }}</p>
    <p>Fecha de publicación: {{ model.pub_date }}</p>
    <a href="{% url 'model:detail_area' model.area.pk %}" class="btn blue">Listado del modelo R01/PG.190-01</a>
    <a href="{% url 'model:update_modelr01pg01' model.pk %}" class="btn blue-grey">Editar</a>
    {% if user.is_superuser %}
        <a href="{% url 'model:delete_modelr01pg01' model.pk %}" class="btn red">Eliminar</a>
    {% endif %}
{% endblock %}

model/templates/model/modelr01pg01_form.html
{% extends 'account/dashboard.html' %}

{% block content-left %}
    <form method="post">
        {% csrf_token %}
        <div class="container-fluid">
            <div class="col l2">
                {{ form.year.errors }}
                {{ form.year.label_tag }}
                {{ form.year }}
            </div>
            <div class="col l10">
                {{ form.environmental_aspects.errors }}
                {{ form.environmental_aspects.label_tag }}
                {{ form.environmental_aspects }}
            </div>
        </div>
        <input type="submit" value="Aceptar" class="btn blue">
        <a href="{% url 'model:list_modelr01pg01' %}" class="btn blue">Listado del modelo R01/PG.190-01</a>
    </form>
{% endblock %}

model/templates/model/modelr01pg01_list.html
{% extends 'account/dashboard.html' %}

{% block title %}
    Area {{ area.name }}
{% endblock %}

{% block content-left %}
    <h4 class="center">Identificación de aspectos ambientales</h4>
    <h5 class="center">Relación de aspectos ambientales</h5>
    <h6 class="left">Area: {{ area.name }}</h6>
    <table class="table">
        <tr>
            <th>No</th>
            <th>Aspectos ambientales</th>
            <th>Registrado por</th>
            <th>Año</th>
            <th>Fecha de publicación</th>
            <th>Acciones</th>
        </tr>
        {% for model in models %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ model }}</td>
                <td><a href="{% url 'account:detail_user' model.register_by.pk %}">{{ model.register_by }}</a></td>
                <td>{{ model.year }}</td>
                <td>{{ model.pub_date }}</td>
                <td colspan="3">
                    <a href="{% url 'model:detail_modelr01pg01' model.pk %}"><i class="material-icons">description</i></a>
                    <a href="{% url 'model:update_modelr01pg01' model.pk %}"><i class="material-icons">edit</i></a>
                    {% if user.is_superuser %}
                        <a href="{% url 'model:delete_modelr01pg01' model.pk %}"><i class="material-icons">delete</i></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'model:create_modelr01pg01' %}" class="btn blue">Añadir modelo</a>
    <a href="{% url 'model:list_all_modelr01pg01' %}" class="btn blue">Ver todos los modelos</a>
    <a href="{% url 'model:list_environmental_matrix' %}" class="btn blue">Ver Matriz de Evaluacion</a>
{% endblock %}

model/templates/model/modelr01pg01_list_all.html
{% extends 'account/dashboard.html' %}
{% block title %}
    Listado de los modelos
{% endblock %}

{% block content-left %}
    <h4 class="center">Todos los modelos</h4>
    <table>
        <tr>
            <th>No</th>
            <th>Area</th>
            <th>año</th>
            <th>registrado por</th>
            <th>fecha publicación</th>
            <th colspan="3">Acciones</th>
        </tr>

        {% for model in model_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'model:detail_area' model.area.pk %}">{{ model.area }}</a></td>
                <td>{{ model.year }}</td>
                <td><a href="{% url 'account:detail_user' model.register_by.pk %}">{{ model.register_by }}</a></td>
                <td>{{ model.pub_date }}</td>
                <td colspan="3">
                    <a href="{% url 'model:detail_modelr01pg01' model.pk %}"><i
                            class="material-icons">description</i></a>
                    {% if user.is_superuser %}
                        <a href="{% url 'model:update_modelr01pg01' model.pk %}"><i class="material-icons">edit</i></a>
                        <a href="{% url 'model:delete_modelr01pg01' model.pk %}"><i class="material-icons">delete</i></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'model:create_modelr01pg01' %}" class="btn blue">Añadir</a>
{% endblock %}